title: John F. Cummings
logo: /assets/logo.png
description: Mechanical Engineering Student at Lehigh University <br><br> Undergraduate Research Assistant <br><br> Formula SAE Design Lead <br><br>Secret Security Clearance 
show_downloads: false
google_analytics: UA-150490434-1 
google_analytics: UA-150490434-2 
theme: jekyll-theme-minimal
